name: Test releases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-tester:
    name: Run Docker Pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        tags: test-image:latest
        push: false
    - uses: addnab/docker-run-action@v3
      with:
        image: test-image:latest
        run: pytest -v
    #- name: Set up Python ${{ matrix.python-version }}
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: ${{ matrix.python-version }}
    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install pytest
    #    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #- name: Run Tests
    #  run: pytest -v
