name: Test releases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-tester:
    name: Run Docker Pytest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build local docker container
      uses: docker/build-push-action@v2
      with:
        tags: test-image:latest
        push: false
    - name: Run tests inside container
      uses: addnab/docker-run-action@v3
      with:
        image: test-image:latest
        run: pytest -v
