name: Test release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-tester:
    name: Docker Test image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Test Image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: anmol1696/klargest:tester
      - name: Run Tests
        uses: addnab/docker-run-action@v3
        with:
          image: anmol1696/klargest:tester
          run: pytest -k -v
